server:
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identityDB?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  spring:
    messages:
      basename: messages
      encoding: utf8

JWT:
  JWT_SECRET: c264386b4ff3d0d2858eef6b3a29727d
  JWT_EXPIRATION: 900000